package-lock.json, package.json, public/index.html, server/server.js, src/components/App.jsx, src/index.js, webpack.config.js
Boilerplate made with the team to get the react app to render and the server to listen at port 3000.
=> boilerplate for the project

.eslintignore, .eslintrc.json, .prettierrc, package-lock.json, package.json, server/server.js, src/index.js, webpack.config.js
This adds the remaining peer dependencies for the ESLint configuration and includes a configuration for prettier.
This allows ESLint config to work properly.
=> Add tweaks for eslint/prettier configuration

package-lock.json, package.json, server/server.js
- This implements the functionality of validating username exists, checking if passwords match, storing the user into database and creating a session for that user.
=> Add backend logic for signup

src/components/SignUp.jsx, src/reducers/userReducer.js
Problem: Enable user to sign up with all the appropriate data about the user sent to the server
Solution: Used Ant Design forms. Redux state updated with successfully made username.
=> Sign Up Done! Works with the backend

src/components/SignUp.jsx
Problem: Error messages on bad signup data look ugly. Fields don't get cleared
Solution: Used Alert ant design component to make it looks better and used setFieldsValue to clear the data
Test: Try signing up with an already existing username.
=> Improved error messages on signup form

src/components/Login.jsx
Problem: Users have no way of logging in once their account is created.
Solution: Implemented a simple login page that takes in a username and password and stores the user in state on a successful log in.
Testing: Go to '/login' and fill out the correct info
=> This adds the frontend login page

server/controllers/usersController.js, src/components/Login.jsx
Problem: Frontend and backend were not linked to handle login correctly.
Solution: Fixed error message handling and async issues with bcrypt.
Test: Try logging in with a good login and a bad login.
=> Loginlinked

server/controllers/favoritesController.js, server/routes/favorites.js
- This commit would allow the user to add a recipe to their favorites list
- Adding the recipe would store it in the database
=> Implement addFavorite functionality in backend

server/controllers/usersController.js, src/actions/actions.js, src/components/Login.jsx, src/components/Nav.jsx, src/components/Profile.jsx, src/components/SignUp.jsx, src/constants/actionTypes.js, src/reducers/userReducer.js
Problem: Users have no way of seeing their user preferences and updating them. 
Nav bar always displays all options.
Solution: Added a profile page where users can see their own prefs and change them.
Nav bar now displays links based on whether or not a user is logged in.
Testing: Log in, go to your user prefs, try updating them.
Bonus: Minor bug fixes with login
=> Profile page

src/App.css, src/components/Homepage.jsx
Problem: Recipes not rendering
Solution: ran the mapping function that loops the recipe rendering into the return statement with the jsx code.
=> recipes rendering

server/controllers/favoritesController.js, server/routes/favorites.js, server/server.js
- This commit provides the backend for the user to get the list of the user's favorite recipes.
=> Get favorites list backend

src/actions/actions.js, src/components/Nav.jsx
Problem: User cannot logout of the application.
Solution: Added a logout button to the nav bar that connects to the backend to log users out.
Testing: Log in with good credentials and then log out using the nav bar.
=> This links the front end to the back end for logging out

server/controllers/usersController.js, server/routes/login.js, server/routes/userinfo.js
Problem: There was no way for user to view or update their preferences
Solution: Make middleware that queries the database for current preferences on post request and updates the database on put request.
Testing: 
-use Postman to send post request with username to /api/user/info (should return all user info except password) 
-use Postman to send put request with all user info except password to /api/user/info (should update info in database, return 200 status)
=> Backend for viewing/updating user preferences

src/components/Homepage.jsx, webpack.config.js
Problem: User wants to know the details of the recipe
Solution: Expand button brings up a modal and fetchs more info about the recipe.
=> Homepage done expect for Favoriting

.gitignore, package-lock.json, package.json, server/models/usersModel.js, server/server.js
- Refactor codebase for .env file to hide sensitive information
=> Setup for .env config file

src/actions/actions.js, src/components/Nav.jsx, src/components/Profile.jsx, src/reducers/userReducer.js
Problem: Logout was acting buggy. Profile page updates were acting buggy.
Solution: Fixed Nav components, fix Profile Component, fixed reducers.
Test: Try logging in, updating your profile settings, then logging out.
=> This fixes bugs with login/logout and profile pages

server/controllers/favoritesController.js
- This commit handles when the user tries to add the same recipe that already exists in their favorites
=> Handle adding duplicate recipe to favorites

server/controllers/favoritesController.js
- Problem: Duplicate recipes in general are prevented from being added not specific to a user
- Solution: Add a query to handle duplicate recipes specific to the user
=> Fix duplicate recipe bug

server/controllers/favoritesController.js, server/routes/favorites.js
Problem: addFavorites was adding a recipe id to the favorites table, but not adding recipe information to the recipe table
Solution: Create an addRecipe controller that adds the favorited recipe details to the recipes table
Testing: Do a POST request to /api/favorites/:username with recipeId, title, summary, source_url, and image. New recipe should appear in recipes table and favorites table.
=> AddRecipe Controller added

src/components/Homepage.jsx
=> Bug fix with double Meta

src/components/Homepage.jsx
Problem: Bug fixes and bad merge
Solution: Reverted changes from bad merge.
=> Fixes bad merge

server/controllers/usersController.js
a one liner...
username wasn't getting passed between middleware chain for addUser.
=> add username to res.locals

src/components/Favorites.jsx
Problem: Icons unclear in favorites page
Solution: Changed icons
=> Changes icons in favorites

src/components/Homepage.jsx
Problem: no user feedback when favorites are saved. 
Solution: Add a **favorite** property to the objects in the **recipes** state variable
Test: Add a favorite. Confirm that the heart turns purple.
=> fav feedback

README.md
Added some details about app functionality, authors, etc. to README.
=> Add some more basic details to README
